version: "3.8"

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile_backend
    volumes:
      - ./backend:/backend
    env_file:
      - backend/.env
    environment:
      DATABASE: database
    networks:
      - web_app_network
    ports:
      - '127.0.0.1:8000:8000'
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15-alpine3.18
    container_name: database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data_db:/var/lib/postgresql/data
    env_file:
      - backend/.env
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - web_app_network
    restart: always


networks:
  web_app_network:
    driver: bridge

volumes:
  data_db: